name: Scriptable
favicon: null
layout_spectrum: 0.16574
typography_spectrum: 0.52651
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00a0d2'
    - '#caebf5'
    - '#8fd5eb'
    - '#46bade'
  brandStrength: 0.125
  lightness: 0.08695589448325336
  saturation: 0.06925979582592845
  rhythmicContrast: 0.46630949480459094
purpose: []
