name: Scriptable
favicon: null
layout_spectrum: 0.16574
typography_spectrum: 0.5277122103143483
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.10045355418697
  lightness: 0.08695589448325336
  saturation: 0.06925979582592845
  rhythmicContrast: 0.46630949480459094
purpose: []
